language: perl
# v0.011_000
perl:
    #- "5.10"
    #- "5.12"
    #- "5.14"
    #- "5.16"
    #- "5.18"
    #- "5.20"
    - "5.22"
    - "5.24"
    # version(s) below are built using Travis-CI Helper
    #- "5.25" 
    #- "blead"

# DEV NOTE, CORRELATION #rp011: update g++ to 4.8 for full C++11 support, including:
# -std=c++11, std::string::pop_back(), etc.

# new Docker container-based Travis-CI stack, currently disabled, does not support update-alternatives
sudo: false
addons:
  apt:
    packages:
      - build-essential
      - libtool
      - g++
      - time
      - libgmp-dev
      - texinfo

#addons:
#    apt:
#       sources:
#           - ubuntu-toolchain-r-test

#matrix:
#    allow_failures:
#        - perl: "5.25"
#        - perl: "blead"

before_install:
  - mkdir /home/travis/bin || true
  - ln -s `which true` /home/travis/bin/cpansign
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  # legacy Travis-CI stack, currently enabled, supports sudo & update-alternatives
  #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  #- sudo apt-get update -qq

install:
  #- apt-get install -qq g++-4.8
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  #- apt-get install libgmp-dev
  # begin Pluto PolyCC
  #- wget https://github.com/wbraswell/pluto-mirror/raw/master/backup/pluto-0.11.4.tar.gz
  #- tar -xzvf pluto-0.11.4.tar.gz
  #- cd pluto-0.11.4/
  #- ./configure && make && make install DESTDIR=~/
  #- cd ..
  # end Pluto PolyCC
  #- apt-get install curl
  - cpanm --quiet --installdeps --notest .
  #- cpan-install --deps       # installs prereqs, including recommends

before_script:
    # NEED REMOVE FOLLOWING 1 LINE when bug is fixed   https://github.com/daoswald/Inline-CPP/issues/38
    - cpanm --quiet --force ExtUtils::CppGuess
    # MODIFY FOLLOWING LINE TO ENABLE TEST_VERBOSE STDOUT DURING `make test`
    - export RPERL_VERBOSE=0
    # UNCOMMENT FOLLOWING LINE TO ENABLE NOISY BUILD DURING `make test`; REQUIRES RPERL_VERBOSE=1 ABOVE
    #- export RPERL_DEBUG=1

# replace default build command "perl Makefile.PL && make test"
# DEV NOTE: TEST_VERBOSE variable for ExtUtils::MakeMaker 'make' command disables suppression of stdout;
# this variable is different than, and inherits the value of, the $RPERL_VERBOSE environmental variable 
script: perl Makefile.PL && make test TEST_VERBOSE=$RPERL_VERBOSE

notifications:
    irc:
        channels:
            - "irc.perl.org#perl11"
        on_success: always
        on_failure: always
        # to enable skip_join, in IRC channel first execute `/mode -n`
        skip_join: true
        template:
            - "RPerl build %{result}. %{author} says '%{commit_message}'"
            - "%{build_url} %{compare_url}"

env:
    global:
        - AUTHOR_TESTING=0
